
class MAINDEF:
    MODE = 'SIMULATION'  # 'SIMULATION' or 'RPI'


class CAMERAS:
    # FRONT CAM 1
    FRONT_CAM_1_NR = 0
    FRONT_CAM_1_RESOLUTION_HEIGHT = 720
    FRONT_CAM_1_RESOLUTION_WIDTH = 1280

    # BOTTOM CAM 1
    BOTTOM_CAMERA_NR = 1
    BOTTOM_CAMERA_RESOLUTION_HEIGHT = 720
    BOTTOM_CAMERA_RESOLUTION_WIDTH = 1280

    # BUMBER LEFT CAM 1
    BUMBER_CAMERA_LEFT_NR = 2
    BUMBER_CAMERA_LEFT_RESOLUTION_HEIGHT = 720
    BUMBER_CAMERA_LEFT_RESOLUTION_WIDTH = 1280

    # BUMBER RIGHT CAM 1
    BUMBER_CAMERA_RIGHT_NR = 3
    BUMBER_CAMERA_RIGHT_RESOLUTION_HEIGHT = 720
    BUMBER_CAMERA_RIGHT_RESOLUTION_WIDTH = 1280

    # ARM RIGHT CAM 1
    ARM_CAMERA_NR = 4
    ARM_CAMERA_RESOLUTION_HEIGHT = 720
    ARM_CAMERA_RESOLUTION_WIDTH = 1280

    # XIAOMI
    XIAOMI_CAMERA_SOURCE = 'rtsp://192.168.42.1/live'

    # SIMULATION
    SIM_BOTTOM_CAM_ID = 1
    SIM_FRONT_CAM_1_ID = 0
