
class MAINDEF:
    MODE = 'SIMULATION' # 'SIMULATION' or 'RPI'

class CAMERAS:
    #FRONT CAM 1
    FRONT_CAM_1_NR = 0
    FRONT_CAM_1_RESOLUTION_HEIGHT = 720
    FRONT_CAM_1_RESOLUTION_WIDTH = 1280
